### ISSUE TITLE
lxd-ui.pfx does not work on a Mac because of empty password. 

### ISSUE THREAD

**Issue by jaminmc** [canonical/lxd-ui#331]
When using any browser on a Mac, it uses the OS for certificates. Macos, at least Ventura doesn't allow blank passwords for PFX files. The easy fix would be for the generator on LXD US to prompt for a password when generating the certs, that way the user can type that in when they add it to the MacOS keychain. 

I did figure out a workaround... 
If I run this in the trerminal on my Mac, it will ass a password to a new file:
`openssl pkcs12 -in lxd-ui.pfx -password pass:"" -passin pass:"" -passout pass:"InsertPasswordHere" -out "lxd-ui-mac.pfx"`

Then all I had to do is double click on the lxd-ui-mac.pfx file, and enter the password I put in above. Now I have access!

**Comment by edlerd** [comment]
Thank you for the report.
Yes, I think we can add an optional password input on generation of the certs in the UI.

**Comment by edlerd** [comment]
We just merged the fix, if you want to give this another try - now we prompt for a (skippable) password on certificate creation.

**Comment by jaminmc** [comment]
Ok, so the password option just gives an error of: "An error has occurred. Unable to import an item. Unknown format in import." So this doesn't fix it... It turns out that the command I use that I though was just adding a password to the new file was actually converting it to a PEM file with it being encrypted with the new password.

The easy fix is to just put in Mac instructions of running `openssl pkcs12 -nodes -in lxd-ui.pfx -out lxd-ui.pem`, or have the LXD UI have a PEM output option.

**Comment by edlerd** [comment]
We are planning to add a tutorial for mac as well and that will give you the key in pem format.

**Comment by jaminmc** [comment]
Ok, the PEM file is not working, as Macos doesn't understand the encryption used. 

It does handle pfx/p12 files just fine, if created with openssl 1.1, or with a -legacy option.
Here is a pfx that was generated from the ui:
```
 openssl pkcs12 -in /tmp/lxd-ui.pfx -info -noout                            
Enter Import Password:
MAC: sha1, Iteration 2048
MAC length: 20, salt length: 8
PKCS7 Data
Certificate bag
PKCS7 Data
Shrouded Keybag: PBES2, PBKDF2, AES-128-CBC, Iteration 2048, PRF hmacWithSHA1
```
And here is the working version:
```
openssl pkcs12 -in /tmp/lxd-ui.p12  -info -legacy -noout
Enter Import Password:
MAC: sha1, Iteration 2048
MAC length: 20, salt length: 8
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 2048
Certificate bag
PKCS7 Data
Shrouded Keybag: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 2048
```
So, if the pfx used the older pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 2048 encryption instead of PBES2, PBKDF2, AES-128-CBC, Iteration 2048, PRF hmacWithSHA1, then the file would work fine with macos. 

Or the key needs to be saved in the PEM unencrypted.

Here is how I generated me p12 file:
```openssl pkcs12 -in /tmp/lxd-ui.pfx -nodes -out /tmp/tmp.pem ;  openssl pkcs12 -legacy -export -in /tmp/tmp.pem -out /tmp/lxd-ui.p12```

Also note, I am using openssl from /opt/homebrew/opt/openssl@3/bin/openssl, not apples.


As far as browsers being able to use the cert then it is correctly added, the browser just needs to be restarted. I can't test it on the demo site, as the crt needs to be imported on it.

![Screenshot 2023-06-07 at 1 00 04 AM](https://github.com/canonical/lxd-ui/assets/1310376/7477601d-bfe1-4f92-b65e-6329f60f2e01)
When properly imported, is shows the Private key with the Browser generated Cert.

**Comment by edlerd** [comment]
Thank you for the detailed explanation. With that at hand, I could quickly make the import and usage work on macOS. Indeed, only the algorithm needs to be changed from aes to 3des for the keychain app to accept the certificate.
